/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class learngl_triangle_TriangleRenderer */

#ifndef _Included_learngl_triangle_TriangleRenderer
#define _Included_learngl_triangle_TriangleRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     learngl_triangle_TriangleRenderer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qianxian_src_DemoRenderer_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     learngl_triangle_TriangleRenderer
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_qianxian_src_DemoRenderer_nativeResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     learngl_triangle_TriangleRenderer
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qianxian_src_DemoRenderer_nativeRender
  (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_qianxian_src_DemoRenderer_nativeSpeed
  (JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
